[package]
name = "pipboytyper"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
soloud = "1.0.5"
termsize = "0.1.9"
thiserror = "1.0.63"

[[bin]]
name = "pipboytyper"
path = "src/main.rs"
